### ISSUE TITLE
Do you have this working?

### ISSUE THREAD

**Issue by alfureu** [bjuretko/docker-baikal-infcloud#1]
Hi @bjuretko, do you have this working, as I would be interested in a docker like this.

**Comment by bjuretko** [comment]
See branch `chore/support-php7` for the current status. I currently got an error when adding new  calenders for users to baikal:

```
PDOException: SQLSTATE[HY000]: General error: 1 table calendars has no column named principaluri in /var/www/baikal/Core/Frameworks/Flake/Core/Database.php:180
Stack trace:
#0 /var/www/baikal/Core/Frameworks/Flake/Core/Database.php(180): PDO->query('INSERT INTO cal...')
#1 /var/www/baikal/Core/Frameworks/Flake/Core/Database.php(40): Flake\Core\Database->query('INSERT INTO cal...')
#2 /var/www/baikal/Core/Frameworks/Flake/Core/Model/Db.php(91): Flake\Core\Database->exec_INSERTquery('calendars', Array)
#3 /var/www/baikal/Core/Frameworks/Baikal/Model/User.php(160): Flake\Core\Model\Db->persist()
#4 /var/www/baikal/Core/Frameworks/Formal/Form.php(226): Baikal\Model\User->persist()
#5 /var/www/baikal/Core/Frameworks/BaikalAdmin/Controller/Users.php(193): Formal\Form->execute()
#6 /var/www/baikal/Core/Frameworks/BaikalAdmin/Controller/Users.php(40): BaikalAdmin\Controller\Users->actionNew()
#7 /var/www/baikal/Core/Frameworks/Flake/Core/Render/Container.php(62): BaikalAdmin\Controller\Users->execute()
#8 /var/www/baikal/Core/Frameworks/Flake/Controller/Page.php(83): Flake\Core\Render\Container->execute()
#9 /var/www/baikal/Core/Frameworks/BaikalAdmin/WWWRoot/index.php(92): Flake\Controller\Page->render()
#10 {main} 
```

The column `principaluri` of table `calendars` is missing in the database. See
![image](https://user-images.githubusercontent.com/30392977/55287295-514aa100-53a7-11e9-985f-1d8681f319f7.png)

Same problem arises with mysql (see docker-compose.yml - you need to uncomment mysql service).
Adding adressbooks is fine, users are added as well...

maybe you have an Idea?

**Comment by alfureu** [comment]
Hi @bjuretko, I am not so skilled in PHP, pretty new to docker, but what I have read so far suggests that it might be just a wrong link, e.g.: [http://sabre.io/baikal/upgrade/](http://sabre.io/baikal/upgrade/) and [https://github.com/sabre-io/Baikal/issues/464](https://github.com/sabre-io/Baikal/issues/464).

In addition, there is another baikal+infcloud docker image, [https://gitlab.com/Plague_Doctor/docker-baikal](https://gitlab.com/Plague_Doctor/docker-baikal), which has exactly the opposite problem, the carddav works, the caldav results in error. Maybe this can be helpful in identifying the issue?

Alternatively, it might be useful to contact the original developer of baikal [https://evertpot.com/](https://evertpot.com/), who states that baikal was successfully running with PHP7. Although I never saw a fully successful running docker.

**Comment by bjuretko** [comment]
Thx for the information ... I pushed the php5 branch - which solves the problem with model creation.
I will work on setting up infcloud and the necessary redirects with it. And then look at php7 again.

**Comment by alfureu** [comment]
Thanks, great. Would you put the docker image on [hub.docker.com](https://hub.docker.com/) as well? I can help in writing the installation instructions, if requred.

**Comment by bjuretko** [comment]
@DOFfactory php5  is merged to master and working for me with bundled infcloud.

**Comment by bjuretko** [comment]
@DOFfactory  you can checkout a first working version with php7 at #13

**Comment by bjuretko** [comment]
Everything is merged to master, project is more or less finalized for me as it runs on all my machines. Thanks for testing and your feedback.
