### ISSUE TITLE
Support php7

### ISSUE THREAD

**Issue by bjuretko** [bjuretko/docker-baikal-infcloud#8]
See branch `chore/support-php7` for the current status. I currently got an error when adding new  calenders for users to baikal:

```
PDOException: SQLSTATE[HY000]: General error: 1 table calendars has no column named principaluri in /var/www/baikal/Core/Frameworks/Flake/Core/Database.php:180
Stack trace:
#0 /var/www/baikal/Core/Frameworks/Flake/Core/Database.php(180): PDO->query('INSERT INTO cal...')
#1 /var/www/baikal/Core/Frameworks/Flake/Core/Database.php(40): Flake\Core\Database->query('INSERT INTO cal...')
#2 /var/www/baikal/Core/Frameworks/Flake/Core/Model/Db.php(91): Flake\Core\Database->exec_INSERTquery('calendars', Array)
#3 /var/www/baikal/Core/Frameworks/Baikal/Model/User.php(160): Flake\Core\Model\Db->persist()
#4 /var/www/baikal/Core/Frameworks/Formal/Form.php(226): Baikal\Model\User->persist()
#5 /var/www/baikal/Core/Frameworks/BaikalAdmin/Controller/Users.php(193): Formal\Form->execute()
#6 /var/www/baikal/Core/Frameworks/BaikalAdmin/Controller/Users.php(40): BaikalAdmin\Controller\Users->actionNew()
#7 /var/www/baikal/Core/Frameworks/Flake/Core/Render/Container.php(62): BaikalAdmin\Controller\Users->execute()
#8 /var/www/baikal/Core/Frameworks/Flake/Controller/Page.php(83): Flake\Core\Render\Container->execute()
#9 /var/www/baikal/Core/Frameworks/BaikalAdmin/WWWRoot/index.php(92): Flake\Controller\Page->render()
#10 {main} 
```

The column `principaluri` of table `calendars` is missing in the database. See
![image](https://user-images.githubusercontent.com/30392977/55287295-514aa100-53a7-11e9-985f-1d8681f319f7.png)

Same problem arises with mysql (see docker-compose.yml - you need to uncomment mysql service).
Adding adressbooks is fine, users are added as well...

maybe you have an Idea?

_Originally posted by @bjuretko in https://github.com/bjuretko/docker-baikal-infcloud/issues/1#issuecomment-478323989_

**Comment by bjuretko** [comment]
Same problem as described here https://gitlab.com/Plague_Doctor/docker-baikal/issues/1

**Comment by bjuretko** [comment]
Version 0.5.2 was released which adressed above mentioned issue.
https://github.com/sabre-io/Baikal/releases/tag/0.5.2

See #13 for an update to latest alpine image with php7 and the above release.
The migration process from 0.4.6 was successfully. 👍 

So for now I can confirm the check matrix in https://github.com/sabre-io/Baikal/pull/768#issuecomment-484250465 for me running this locally.
